name: Update Secret Value

on:
  push:
    branches:
      - main

jobs:
  update-secret:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Print secret
      env:
        KEY_API_OPENAI: ${{ secrets.KEY_API_OPENAI }}
      run: echo "The secret value is $KEY_API_OPENAI"

    - name: Create .env file
      run: echo "MY_SECRET_VALUE=${{ secrets.KEY_API_OPENAI }}" > .env
